repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python run_tests.py fast
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: lint
        name: lint
        entry: python -m flake8 bot/ tests/
        language: system
        pass_filenames: true
        stages: [pre-commit]
        
      - id: format
        name: format
        entry: python -m black bot/ tests/
        language: system
        pass_filenames: true
        stages: [pre-commit]
